# These are supported funding model platforms

github: https://github.com/khushhal13
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: https://khushhalportfolio.netlify.app
